import { Bank } from '../types';

export const initialBanks: Bank[] = [
  {
    id: 'alahli',
    nameAr: 'البنك الأهلي السعودي',
    nameEn: 'SNB',
    logoColor: 'from-emerald-700 to-emerald-950',
    logoText: 'الأهلي',
    isActive: true,
    calendarType: 'gregorian',
    maxTermMonths: 360,
    maxAgeAtEnd: 75,
    monthsAfterRetirement: 180,
    allowAfterRetirement: true,
    displayOrder: 1,
    internalNotes: 'متوافق مع الشريعة الإسلامية بالكامل لعقود الإجارة والمرابحة.'
  },
  {
    id: 'rajhi',
    nameAr: 'مصرف الراجحي',
    nameEn: 'Al Rajhi Bank',
    logoColor: 'from-blue-700 to-blue-950',
    logoText: 'الراجحي',
    isActive: true,
    calendarType: 'hijri',
    maxTermMonths: 360,
    maxAgeAtEnd: 75,
    monthsAfterRetirement: 265,
    allowAfterRetirement: true,
    displayOrder: 2,
    internalNotes: 'أكبر محفظة تمويل عقاري في المملكة.'
  },
  {
    id: 'alinma',
    nameAr: 'مصرف الإنماء',
    nameEn: 'Alinma Bank',
    logoColor: 'from-amber-600 to-amber-950',
    logoText: 'الإنماء',
    isActive: true,
    calendarType: 'hijri',
    maxTermMonths: 360,
    maxAgeAtEnd: 70,
    monthsAfterRetirement: 0,
    allowAfterRetirement: false,
    displayOrder: 3,
    internalNotes: 'أسرع موافقات ائتمانية على مستوى البنوك.'
  },
  {
    id: 'fransi',
    nameAr: 'البنك السعودي الفرنسي',
    nameEn: 'BSF',
    logoColor: 'from-cyan-600 to-cyan-950',
    logoText: 'الفرنسي',
    isActive: true,
    calendarType: 'gregorian',
    maxTermMonths: 360,
    maxAgeAtEnd: 65,
    monthsAfterRetirement: 73,
    allowAfterRetirement: true,
    displayOrder: 4,
    internalNotes: 'يركز على قطاع الموظفين الحكوميين والشركات الكبرى.'
  },
  {
    id: 'bidaya',
    nameAr: 'بداية لتمويل المنازل',
    nameEn: 'Bidaya Finance',
    logoColor: 'from-rose-600 to-rose-950',
    logoText: 'بداية',
    isActive: true,
    calendarType: 'hijri',
    maxTermMonths: 240,
    maxAgeAtEnd: 65,
    monthsAfterRetirement: 0,
    allowAfterRetirement: false,
    displayOrder: 5,
    internalNotes: 'شركة تمويل عقاري غير مصرفية برعاية حكومية.'
  },
  {
    id: 'albilad',
    nameAr: 'بنك البلاد',
    nameEn: 'Bank Albilad',
    logoColor: 'from-teal-600 to-teal-950',
    logoText: 'البلاد',
    isActive: true,
    calendarType: 'hijri',
    maxTermMonths: 360,
    maxAgeAtEnd: 70,
    monthsAfterRetirement: 180,
    allowAfterRetirement: true,
    displayOrder: 6,
    internalNotes: 'حلول تمويل عقاري بصيغ متعددة.'
  },
  {
    id: 'alarabi',
    nameAr: 'البنك العربي الوطني',
    nameEn: 'ANB',
    logoColor: 'from-indigo-700 to-indigo-950',
    logoText: 'العربي',
    isActive: true,
    calendarType: 'gregorian',
    maxTermMonths: 360,
    maxAgeAtEnd: 70,
    monthsAfterRetirement: 180,
    allowAfterRetirement: true,
    displayOrder: 7,
    internalNotes: 'عروض منافسة لهوامش الأرباح العقارية.'
  }
];
