import { ProductAcceptance } from '../types';

export const initialProductAcceptance: ProductAcceptance[] = [
  // --- SNB (AlAhli) Acceptances ---
  {
    id: 'snb_re_only',
    bankId: 'alahli',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'military', 'private'],
    minAge: 18,
    maxAge: 70,
    minSalary: 5000,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'البنك الأهلي: يتطلب راتب لا يقل عن 5,000 ريال وعمر بين 18 و70، مع مدة خدمة 3 أشهر كحد أدنى.'
  },
  {
    id: 'snb_pf_only',
    bankId: 'alahli',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'البنك الأهلي: لا يتاح التمويل الشخصي إلا للموظفين والمتقاعدين النشطين براتب لا يقل عن 4,000 ريال وخدمة شهر واحد.'
  },
  {
    id: 'snb_re_new_pf',
    bankId: 'alahli',
    productId: 'real_estate_with_new_personal',
    allowedSectors: ['government_civilian', 'military', 'private'],
    minAge: 21,
    maxAge: 60,
    minSalary: 8000,
    minServiceMonths: 6,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: false,
    isActive: true,
    defaultRejectionMessage: 'البنك الأهلي: التمويل المشترك (عقاري + شخصي جديد) يتطلب حد أدنى للراتب 8,000 ريال وعمر لا يقل عن 21 عاماً مع خدمة 6 أشهر.'
  },
  {
    id: 'snb_re_existing_pf',
    bankId: 'alahli',
    productId: 'real_estate_with_existing_personal',
    allowedSectors: ['government_civilian', 'military', 'private'],
    minAge: 21,
    maxAge: 65,
    minSalary: 6000,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'البنك الأهلي: تمويل عقاري بوجود شخصي قائم يتطلب راتب 6,000 ريال كحد أدنى وعمر لا يقل عن 21 عاماً.'
  },

  // --- AlRajhi Acceptances ---
  {
    id: 'rajhi_re_only',
    bankId: 'rajhi',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 75,
    minSalary: 3000,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'مصرف الراجحي: الحد الأدنى لراتب التمويل العقاري هو 3,000 ريال وتجند خدمة لا تقل عن 3 أشهر.'
  },
  {
    id: 'rajhi_pf_only',
    bankId: 'rajhi',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'مصرف الراجحي: الحد الأدنى للتمويل الشخصي للقبول هو راتب قدره 4,000 ريال وعمر بين 18 و65 سنة.'
  },
  {
    id: 'rajhi_re_new_pf',
    bankId: 'rajhi',
    productId: 'real_estate_with_new_personal',
    allowedSectors: ['government_civilian', 'military', 'private'],
    minAge: 20,
    maxAge: 60,
    minSalary: 6000,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: false,
    isActive: true,
    defaultRejectionMessage: 'مصرف الراجحي: باقة العقاري + الشخصي الجديد تتطلب راتب لا يقل عن 6,000 ريال عائداً وعمر 20 على الأقل.'
  },
  {
    id: 'rajhi_re_existing_pf',
    bankId: 'rajhi',
    productId: 'real_estate_with_existing_personal',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 70,
    minSalary: 4500,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'مصرف الراجحي: باقة عقاري مع شخصي قائم تتطلب تصفية راتب لا يقل عن 4,500 ريال وعمر لا يزيد عن 70.'
  },

  // --- AlInma Acceptances ---
  {
    id: 'alinma_re_only',
    bankId: 'alinma',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 75,
    minSalary: 6000,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'مصرف الإنماء: يستلزم راتباً بقيمة 6,000 ريال فما فوق وعمر لا يجاوز الـ 75 عاماً لمسار العقاري.'
  },
  {
    id: 'alinma_pf_only',
    bankId: 'alinma',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'مصرف الإنماء: الحد الأدنى للتمويل الشخصي هو 4,000 ريال ولا يقل عن 1 أشهر خدمة للقطاع المسموح.'
  },

  // --- Frenchman (Fransi) Acceptances ---
  {
    id: 'fransi_re_only',
    bankId: 'fransi',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'private'],
    minAge: 22,
    maxAge: 70,
    minSalary: 7000,
    minServiceMonths: 6,
    allowMonthlySupport: true,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: false,
    isActive: true,
    defaultRejectionMessage: 'البنك الفرنسي: لا يخدم القطاع العسكري أو المتقاعدين للتمويل الجديد، والحد الأدنى للراتب هو 7,000 ريال.'
  },
  {
    id: 'fransi_pf_only',
    bankId: 'fransi',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'البنك الفرنسي: التمويل الشخصي يتطلب راتباً لا يقل عن 4,000 ريال وعمر بين 18 و65 سنة.'
  },

  // --- Bidaya Acceptances ---
  {
    id: 'bidaya_re_only',
    bankId: 'bidaya',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'military', 'private'],
    minAge: 21,
    maxAge: 65,
    minSalary: 4500,
    minServiceMonths: 6,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: false,
    isActive: true,
    defaultRejectionMessage: 'شركة بداية لا تقدم هذا المنتج للمتقاعدين.'
  },
  {
    id: 'bidaya_pf_only',
    bankId: 'bidaya',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'شركة بداية: التمويل الشخصي يتطلب راتباً لا يقل عن 4,000 ريال وعمر بين 18 و65 سنة.'
  },

  // --- AlBilad Acceptances ---
  {
    id: 'albilad_re_only',
    bankId: 'albilad',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 70,
    minSalary: 5000,
    minServiceMonths: 3,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'بنك البلاد: يشترط راتب لا يقل عن 5,000 ريال وعمر لا يزيد عن 70 للتمويل العقاري.'
  },
  {
    id: 'albilad_pf_only',
    bankId: 'albilad',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'بنك البلاد: التمويل الشخصي يتطلب راتباً لا يقل عن 4,000 ريال وعمر بين 18 و65 سنة.'
  },

  // --- Arab National Bank (Alarabi) Acceptances ---
  {
    id: 'alarabi_re_only',
    bankId: 'alarabi',
    productId: 'real_estate_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 20,
    maxAge: 70,
    minSalary: 6000,
    minServiceMonths: 6,
    allowMonthlySupport: true,
    allowDownpaymentSupport: true,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'البنك العربي: يتطلب خدمة لا تقل عن 6 أشهر للقطاع الخاص وراتب 6,000 ريال كحد أدنى.'
  },
  {
    id: 'alarabi_pf_only',
    bankId: 'alarabi',
    productId: 'personal_only',
    allowedSectors: ['government_civilian', 'military', 'private', 'retired'],
    minAge: 18,
    maxAge: 65,
    minSalary: 4000,
    minServiceMonths: 1,
    allowMonthlySupport: false,
    allowDownpaymentSupport: false,
    allowUnsupported: true,
    allowAfterRetirement: true,
    isActive: true,
    defaultRejectionMessage: 'البنك العربي: التمويل الشخصي يتطلب راتباً لا يقل عن 4,000 ريال وعمر بين 18 و65 سنة.'
  }
];
